name: Etihad AgentApp Azure App Service Publish

# Execute workflow on a new release
# Please create a repo secret named agentpubprofile and contents of Webapp publishprofile
on:
  release:
    types: [created]

env:
  AZURE_WEBAPP_NAME: agentapp         # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy - AgentApp Server Side
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: 'Deploy to AgentApp Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.agentpubprofile }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
